@startuml School

title Canica - School Domain

class Student {
  string id
  string name
}

class SchoolYear {
  int startYear
  int finishYear
}

class SchoolClass << Aggregate >>{
  string id
  string name
  
  addStudent(student)
}

class Area {
  string id
  string name
}

class Dimension {
  string id
  string name
}

class Grade {
  string value
}

class SchoolClassRepository {
  findClassById(schoolId): SchoolClass
  findClassByYear(schoolYear): SchoolClass[]
  
  exists(schoolClass): boolean
  save(schoolClass): void
  delete(schoolClass): void
}


SchoolClassRepository --> SchoolClass
SchoolClass "1" -- "1" SchoolYear
SchoolClass "*" -- "1" Area
Dimension o-- Area
SchoolClass "1..*" -- "*..1" Student
(SchoolClass, Student, Area) .. Grade

@enduml