export * from "./area";
export * from "./area-repository";
export * from "./dimension";
export * from "./evaluation";
export * from "./evaluation-repository";
export * from "./quarter";
export * from "./school-term";
export * from "./student";
export * from "./students-group";
